services:
  terrad:
    image: terra:latest
    build:
      dockerfile: Dockerfile
      args:
        RUNNER_IMAGE: alpine
    volumes:
      - $HOME/.terra/:/terra/.terra/
    container_name: terrad-node
    restart: always
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656-26657:26656-26657"
    command:
      - start
    networks:
      terranet:
        ipv4_address: 192.168.10.2

networks:
  terranet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/24
